name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            install: sudo apt-get update && sudo apt-get install -y libncurses-dev
          - os: macos-latest
            install: brew install ncurses

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install ncurses dependency
      run: ${{ matrix.install }}
    - name: Build with make
      run: make
    - name: Clean workspace
      run: make clean
